"""init models

Revision ID: f12f680ca35d
Revises: 20bfe630773e
Create Date: 2026-05-27 00:04:27.912379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f12f680ca35d'
down_revision: Union[str, Sequence[str], None] = '20bfe630773e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amenities_id'), 'amenities', ['id'], unique=False)
    op.create_table('cafe_types',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cafe_types_id'), 'cafe_types', ['id'], unique=False)
    op.create_index(op.f('ix_cafe_types_slug'), 'cafe_types', ['slug'], unique=True)
    op.create_table('cities',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('province', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cities_id'), 'cities', ['id'], unique=False)
    op.create_index(op.f('ix_cities_slug'), 'cities', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('CUSTOMER', 'CAFE_OWNER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'BLOCKED', 'DELETED', name='userstatus'), nullable=False),
    sa.Column('phone_verified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('cafe_owner_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('national_code', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_cafe_owner_profiles_national_code'), 'cafe_owner_profiles', ['national_code'], unique=True)
    op.create_table('cafes',
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('cafe_type_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address_text', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('price_level', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=False),
    sa.Column('reviews_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'REJECTED', 'DELETED', name='cafestatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cafe_type_id'], ['cafe_types.id'], ),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cafes_cafe_type_id'), 'cafes', ['cafe_type_id'], unique=False)
    op.create_index(op.f('ix_cafes_city_id'), 'cafes', ['city_id'], unique=False)
    op.create_index(op.f('ix_cafes_id'), 'cafes', ['id'], unique=False)
    op.create_index(op.f('ix_cafes_name'), 'cafes', ['name'], unique=False)
    op.create_index(op.f('ix_cafes_owner_user_id'), 'cafes', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_cafes_slug'), 'cafes', ['slug'], unique=True)
    op.create_table('otp_codes',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Enum('REGISTER', 'LOGIN', name='otppurpose'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_codes_id'), 'otp_codes', ['id'], unique=False)
    op.create_index(op.f('ix_otp_codes_phone'), 'otp_codes', ['phone'], unique=False)
    op.create_index(op.f('ix_otp_codes_user_id'), 'otp_codes', ['user_id'], unique=False)
    op.create_table('cafe_amenities',
    sa.Column('cafe_id', sa.Integer(), nullable=False),
    sa.Column('amenity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], ),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id'], ),
    sa.PrimaryKeyConstraint('cafe_id', 'amenity_id')
    )
    op.create_table('cafe_contacts',
    sa.Column('cafe_id', sa.Integer(), nullable=False),
    sa.Column('contact_type', sa.Enum('PHONE', 'WEBSITE', 'TELEGRAM', 'INSTAGRAM', 'MENU_URL', 'OTHER', name='contacttype'), nullable=False),
    sa.Column('contact_value', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cafe_contacts_cafe_id'), 'cafe_contacts', ['cafe_id'], unique=False)
    op.create_index(op.f('ix_cafe_contacts_id'), 'cafe_contacts', ['id'], unique=False)
    op.create_table('opening_hours',
    sa.Column('cafe_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('opens_at', sa.Time(), nullable=True),
    sa.Column('closes_at', sa.Time(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opening_hours_cafe_id'), 'opening_hours', ['cafe_id'], unique=False)
    op.create_index(op.f('ix_opening_hours_id'), 'opening_hours', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opening_hours_id'), table_name='opening_hours')
    op.drop_index(op.f('ix_opening_hours_cafe_id'), table_name='opening_hours')
    op.drop_table('opening_hours')
    op.drop_index(op.f('ix_cafe_contacts_id'), table_name='cafe_contacts')
    op.drop_index(op.f('ix_cafe_contacts_cafe_id'), table_name='cafe_contacts')
    op.drop_table('cafe_contacts')
    op.drop_table('cafe_amenities')
    op.drop_index(op.f('ix_otp_codes_user_id'), table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_phone'), table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_id'), table_name='otp_codes')
    op.drop_table('otp_codes')
    op.drop_index(op.f('ix_cafes_slug'), table_name='cafes')
    op.drop_index(op.f('ix_cafes_owner_user_id'), table_name='cafes')
    op.drop_index(op.f('ix_cafes_name'), table_name='cafes')
    op.drop_index(op.f('ix_cafes_id'), table_name='cafes')
    op.drop_index(op.f('ix_cafes_city_id'), table_name='cafes')
    op.drop_index(op.f('ix_cafes_cafe_type_id'), table_name='cafes')
    op.drop_table('cafes')
    op.drop_index(op.f('ix_cafe_owner_profiles_national_code'), table_name='cafe_owner_profiles')
    op.drop_table('cafe_owner_profiles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_cities_slug'), table_name='cities')
    op.drop_index(op.f('ix_cities_id'), table_name='cities')
    op.drop_table('cities')
    op.drop_index(op.f('ix_cafe_types_slug'), table_name='cafe_types')
    op.drop_index(op.f('ix_cafe_types_id'), table_name='cafe_types')
    op.drop_table('cafe_types')
    op.drop_index(op.f('ix_amenities_id'), table_name='amenities')
    op.drop_table('amenities')
    # ### end Alembic commands ###
